# Generated by Django 2.1.4 on 2019-01-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_name', models.CharField(max_length=20)),
                ('user', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(default='', max_length=60)),
                ('user', models.CharField(default='', max_length=60)),
                ('calories', models.IntegerField(default=0)),
                ('totalfat', models.IntegerField(default=0)),
                ('saturatedfat', models.IntegerField(default=0)),
                ('transfat', models.IntegerField(default=0)),
                ('carbs', models.IntegerField(default=0)),
                ('cholestorol', models.IntegerField(default=0)),
                ('sodium', models.IntegerField(default=0)),
                ('fiber', models.IntegerField(default=0)),
                ('sugars', models.IntegerField(default=0)),
                ('protein', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=20)),
                ('user', models.CharField(default='', max_length=60)),
                ('foods', models.ManyToManyField(to='meals.Food')),
            ],
        ),
        migrations.AddField(
            model_name='diet',
            name='meals',
            field=models.ManyToManyField(to='meals.Meal'),
        ),
    ]
